version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /data01/graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server
    volumes:
      - /data01/graylog/data/journal:/usr/share/graylog/data/journal
      - /data01/graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: vacsovacsovacsovacso
      GRAYLOG_ROOT_PASSWORD_SHA2: 2b55656e7f27daa99a7014bd4830ac435a02a763bcc09a14232141d60abe4f83
      GRAYLOG_WEB_ENDPOINT_URI: http://www1.las1.vacso.com:9000/api/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
